import { nanoid } from 'nanoid';
import type { KnowledgeNode, KnowledgeEdge, GraphChanges } from '@/types';
import type { GraphParseResult } from '@/schemas';

/**
 * 将图谱解析结果转换为可应用的 GraphChanges
 */
export function buildGraphChanges(
  parseResult: GraphParseResult,
  existingNodes: KnowledgeNode[],
  boardId: string
): GraphChanges {
  const newNodes: KnowledgeNode[] = [];
  const newEdges: KnowledgeEdge[] = [];
  const updatedNodes: { id: string; updates: Partial<KnowledgeNode> }[] = [];
  const now = new Date().toISOString();

  // 创建 title -> node 映射（含新节点）
  const titleToNode = new Map<string, KnowledgeNode>();
  for (const node of existingNodes) {
    titleToNode.set(node.title, node);
  }

  // 处理新节点
  for (const parsed of parseResult.newNodes) {
    const node: KnowledgeNode = {
      id: nanoid(),
      boardId,
      type: parsed.type,
      title: parsed.title,
      content: parsed.content,
      level: parsed.level,
      status: 'lit',
      position: calculatePosition(parsed.relatedNodeTitles, titleToNode, existingNodes),
      metadata: {
        createdAt: now,
        updatedAt: now,
      },
    };
    newNodes.push(node);
    titleToNode.set(node.title, node);
  }

  // 处理更新节点
  for (const updated of parseResult.updatedNodes) {
    const existing = existingNodes.find((n) => n.title === updated.title);
    if (existing) {
      updatedNodes.push({
        id: existing.id,
        updates: {
          content: existing.content + '\n\n' + updated.additionalContent,
          metadata: { ...existing.metadata, updatedAt: now },
        },
      });
    }
  }

  // 处理新边
  for (const edge of parseResult.newEdges) {
    const sourceNode = titleToNode.get(edge.sourceTitle);
    const targetNode = titleToNode.get(edge.targetTitle);
    if (sourceNode && targetNode && sourceNode.id !== targetNode.id) {
      newEdges.push({
        id: nanoid(),
        boardId,
        source: sourceNode.id,
        target: targetNode.id,
        relation: edge.relation,
        type: edge.type,
        autoGenerated: true,
      });
    }
  }

  // 为新节点创建与关联节点的边
  for (const parsed of parseResult.newNodes) {
    const newNode = titleToNode.get(parsed.title);
    if (!newNode) continue;
    for (const relatedTitle of parsed.relatedNodeTitles) {
      const relatedNode = titleToNode.get(relatedTitle);
      if (relatedNode && relatedNode.id !== newNode.id) {
        // 避免重复边
        const edgeExists = newEdges.some(
          (e) =>
            (e.source === newNode.id && e.target === relatedNode.id) ||
            (e.source === relatedNode.id && e.target === newNode.id)
        );
        if (!edgeExists) {
          newEdges.push({
            id: nanoid(),
            boardId,
            source: relatedNode.id,
            target: newNode.id,
            relation: '相关',
            type: 'association',
            autoGenerated: true,
          });
        }
      }
    }
  }

  return { newNodes, updatedNodes, newEdges };
}

/**
 * 计算新节点位置：基于关联节点的平均位置 + 随机偏移
 */
function calculatePosition(
  relatedTitles: string[],
  titleToNode: Map<string, KnowledgeNode>,
  existingNodes: KnowledgeNode[]
): { x: number; y: number } {
  const relatedNodes = relatedTitles
    .map((t) => titleToNode.get(t))
    .filter((n): n is KnowledgeNode => n !== undefined);

  if (relatedNodes.length > 0) {
    const avgX = relatedNodes.reduce((sum, n) => sum + n.position.x, 0) / relatedNodes.length;
    const avgY = relatedNodes.reduce((sum, n) => sum + n.position.y, 0) / relatedNodes.length;
    return {
      x: avgX + randomOffset(-180, 180),
      y: avgY + randomOffset(-120, 120),
    };
  }

  // 无关联节点时，放在已有节点附近或原点附近
  if (existingNodes.length > 0) {
    const lastNode = existingNodes[existingNodes.length - 1];
    return {
      x: lastNode.position.x + randomOffset(-200, 200),
      y: lastNode.position.y + randomOffset(-200, 200),
    };
  }

  return { x: randomOffset(-100, 100), y: randomOffset(-100, 100) };
}

function randomOffset(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

/**
 * 调用图谱解析 API 并应用结果
 */
export async function parseConversationToGraph(
  messages: { role: string; content: string }[],
  existingNodes: KnowledgeNode[],
  boardId: string
): Promise<GraphChanges | null> {
  try {
    const res = await fetch('/api/graph/parse', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        conversation: messages,
        existingNodes: existingNodes.map((n) => ({ id: n.id, title: n.title })),
      }),
    });

    if (!res.ok) return null;

    const parseResult: GraphParseResult = await res.json();
    return buildGraphChanges(parseResult, existingNodes, boardId);
  } catch (error) {
    console.error('Failed to parse conversation:', error);
    return null;
  }
}
