import { nanoid } from 'nanoid';
import type { KnowledgeNode, KnowledgeEdge, GraphChanges } from '@/types';
import type { GraphParseResult } from '@/schemas';

/**
 * 将图谱解析结果转换为可应用的 GraphChanges
 * @param existingEdges 当前已有的边，用于过滤过密连接
 */
export function buildGraphChanges(
  parseResult: GraphParseResult,
  existingNodes: KnowledgeNode[],
  boardId: string,
  existingEdges: KnowledgeEdge[] = []
): GraphChanges {
  const newNodes: KnowledgeNode[] = [];
  const newEdges: KnowledgeEdge[] = [];
  const updatedNodes: { id: string; updates: Partial<KnowledgeNode> }[] = [];
  const now = new Date().toISOString();

  // 构建已有连接节点集合：只允许给“孤立节点”（没有任何边的节点）创建新边
  const connectedNodeIds = new Set<string>();
  for (const edge of existingEdges) {
    connectedNodeIds.add(edge.source);
    connectedNodeIds.add(edge.target);
  }

  // 创建 title -> node 映射（含新节点）
  const titleToNode = new Map<string, KnowledgeNode>();
  for (const node of existingNodes) {
    titleToNode.set(node.title, node);
  }

  // 注意：自动归纳不创建新节点，只建立已有节点间的连接
  // parseResult.newNodes 被忽略，新节点应由用户主动通过“生成节点”按钮创建

  // 处理更新节点
  for (const updated of parseResult.updatedNodes) {
    const existing = existingNodes.find((n) => n.title === updated.title);
    if (existing) {
      updatedNodes.push({
        id: existing.id,
        updates: {
          content: existing.content + '\n\n' + updated.additionalContent,
          metadata: { ...existing.metadata, updatedAt: now },
        },
      });
    }
  }

  // 处理新边：仅当至少一端是孤立节点时才创建边，避免过密连接
  for (const edge of parseResult.newEdges) {
    const sourceNode = titleToNode.get(edge.sourceTitle);
    const targetNode = titleToNode.get(edge.targetTitle);
    if (sourceNode && targetNode && sourceNode.id !== targetNode.id) {
      // 如果两端都已有连接，跳过
      if (connectedNodeIds.has(sourceNode.id) && connectedNodeIds.has(targetNode.id)) continue;
      newEdges.push({
        id: nanoid(),
        boardId,
        source: sourceNode.id,
        target: targetNode.id,
        relation: edge.relation,
        type: edge.type,
        autoGenerated: true,
      });
      // 新边创建后，将两端标记为已连接
      connectedNodeIds.add(sourceNode.id);
      connectedNodeIds.add(targetNode.id);
    }
  }

  // 为新节点创建关联边的逻辑已移除（归纳不创建新节点）

  return { newNodes, updatedNodes, newEdges };
}

/**
 * 计算新节点位置：基于关联节点的平均位置 + 随机偏移
 */
function calculatePosition(
  relatedTitles: string[],
  titleToNode: Map<string, KnowledgeNode>,
  existingNodes: KnowledgeNode[]
): { x: number; y: number } {
  const relatedNodes = relatedTitles
    .map((t) => titleToNode.get(t))
    .filter((n): n is KnowledgeNode => n !== undefined);

  if (relatedNodes.length > 0) {
    const avgX = relatedNodes.reduce((sum, n) => sum + n.position.x, 0) / relatedNodes.length;
    const avgY = relatedNodes.reduce((sum, n) => sum + n.position.y, 0) / relatedNodes.length;
    return {
      x: avgX + randomOffset(-180, 180),
      y: avgY + randomOffset(-120, 120),
    };
  }

  // 无关联节点时，放在已有节点附近或原点附近
  if (existingNodes.length > 0) {
    const lastNode = existingNodes[existingNodes.length - 1];
    return {
      x: lastNode.position.x + randomOffset(-200, 200),
      y: lastNode.position.y + randomOffset(-200, 200),
    };
  }

  return { x: randomOffset(-100, 100), y: randomOffset(-100, 100) };
}

function randomOffset(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

/**
 * 调用图谱解析 API 并应用结果
 */
export async function parseConversationToGraph(
  messages: { role: string; content: string }[],
  existingNodes: KnowledgeNode[],
  boardId: string,
  existingEdges: KnowledgeEdge[] = []
): Promise<GraphChanges | null> {
  try {
    const res = await fetch('/api/graph/parse', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        conversation: messages,
        existingNodes: existingNodes.map((n) => ({ id: n.id, title: n.title })),
      }),
    });

    if (!res.ok) return null;

    const parseResult: GraphParseResult = await res.json();
    return buildGraphChanges(parseResult, existingNodes, boardId, existingEdges);
  } catch (error) {
    console.error('Failed to parse conversation:', error);
    return null;
  }
}
