'use client';

import { useState } from 'react';
import { useUIStore } from '@/stores/uiStore';
import { useGraphStore } from '@/stores/graphStore';
import { useBoardStore } from '@/stores/boardStore';
import { useSettingsStore } from '@/stores/settingsStore';
import { apiFetch } from '@/lib/directApi';
import { nanoid } from 'nanoid';
import { X, Globe, Loader2 } from 'lucide-react';
import type { KnowledgeNode, KnowledgeEdge } from '@/types';

export function DomainModal() {
  const { domainModalOpen, closeDomainModal } = useUIStore();
  const { applyGraphChanges } = useGraphStore();
  const { currentBoardId } = useBoardStore();
  const { apiKey } = useSettingsStore();
  const [domainName, setDomainName] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  if (!domainModalOpen) return null;

  const handleGenerate = async () => {
    if (!domainName.trim()) return;
    setIsLoading(true);
    try {
      const res = await apiFetch('/api/domain', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ domain: domainName.trim(), depth: 3, apiKey: apiKey || undefined }),
      });
      if (!res.ok) throw new Error('生成失败');
      const data = await res.json();

      // 将 API 返回的节点转换为 KnowledgeNode[]
      const now = new Date().toISOString();
      const titleToId = new Map<string, string>();

      // 按层级分组，用于布局计算
      const levelGroups = new Map<number, typeof data.nodes>();
      for (const n of data.nodes) {
        if (!levelGroups.has(n.level)) {
          levelGroups.set(n.level, []);
        }
        levelGroups.get(n.level)!.push(n);
      }

      const newNodes: KnowledgeNode[] = data.nodes.map((n: { title: string; content: string; type: 'concept' | 'theme'; level: number }) => {
        const id = nanoid();
        titleToId.set(n.title, id);

        // 简单树形布局：根节点居中，每层向下偏移 150px，同层水平间距 200px
        const siblings = levelGroups.get(n.level) || [];
        const indexInLevel = siblings.indexOf(n);
        const totalInLevel = siblings.length;
        const x = 400 + (indexInLevel - (totalInLevel - 1) / 2) * 200;
        const y = 100 + n.level * 150;

        return {
          id,
          boardId: currentBoardId || '',
          type: n.type,
          title: n.title,
          content: n.content,
          level: n.level,
          status: 'lit' as const,
          position: { x, y },
          metadata: {
            domainId: nanoid(),
            createdAt: now,
            updatedAt: now,
          },
        };
      });

      // 转换边
      const newEdges: KnowledgeEdge[] = data.edges
        .filter((e: { sourceTitle: string; targetTitle: string }) =>
          titleToId.has(e.sourceTitle) && titleToId.has(e.targetTitle)
        )
        .map((e: { sourceTitle: string; targetTitle: string; relation: string; type: 'hierarchy' | 'association' }) => ({
          id: nanoid(),
          boardId: currentBoardId || '',
          source: titleToId.get(e.sourceTitle)!,
          target: titleToId.get(e.targetTitle)!,
          relation: e.relation,
          type: e.type,
          autoGenerated: true,
        }));

      applyGraphChanges({ newNodes, updatedNodes: [], newEdges });
      closeDomainModal();
      setDomainName('');
    } catch (error) {
      console.error(error);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-[100]">
      <div className="bg-[var(--bg-secondary)] rounded-xl p-6 w-[400px] shadow-2xl shadow-black/30 border border-[var(--border)]">
        {/* 标题 + 关闭按钮 */}
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-lg font-semibold text-[var(--text-primary)] flex items-center gap-2">
            <Globe size={20} className="text-[var(--accent)]" />
            生成领域图谱
          </h2>
          <button
            onClick={closeDomainModal}
            className="p-1 rounded-md hover:bg-[var(--bg-hover)] text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors"
          >
            <X size={18} />
          </button>
        </div>

        {/* 输入框 */}
        <input
          type="text"
          value={domainName}
          onChange={(e) => setDomainName(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === 'Enter' && !isLoading) handleGenerate();
          }}
          placeholder={'输入领域名称，如"机器学习"'}
          className="w-full px-3 py-2 border border-[var(--border-strong)] rounded-lg text-sm bg-[var(--bg-tertiary)] text-[var(--text-primary)] placeholder-[var(--text-muted)] focus:outline-none focus:ring-2 focus:ring-[var(--accent)] focus:border-transparent"
          disabled={isLoading}
        />

        {/* 生成按钮 */}
        <button
          onClick={handleGenerate}
          disabled={isLoading || !domainName.trim()}
          className="mt-4 w-full flex items-center justify-center gap-2 px-4 py-2.5 bg-[var(--accent)] text-white text-sm font-medium rounded-lg hover:bg-[var(--accent-hover)] disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
        >
          {isLoading ? (
            <>
              <Loader2 size={16} className="animate-spin" />
              生成中...
            </>
          ) : (
            <>
              <Globe size={16} />
              生成图谱
            </>
          )}
        </button>
      </div>
    </div>
  );
}
