// ===== 画板类型 =====
export interface Board {
  id: string;
  name: string;
  createdAt: string;
}

// ===== 节点类型 =====
export type NodeType = 'concept' | 'theme' | 'material' | 'understanding' | 'question';
export type NodeStatus = 'lit' | 'unlit';
export type MaterialType = 'article' | 'video' | 'pdf' | 'docx' | 'xlsx' | 'pptx' | 'markdown';

export interface KnowledgeNode {
  id: string;
  boardId: string;
  type: NodeType;
  title: string;
  content: string;
  level: number;
  status: NodeStatus;
  position: { x: number; y: number };
  parentId?: string;
  contentCategory?: 'knowledge' | 'trivia';  // 知识 vs 趣闻
  summary?: string;                            // AI 摘要
  fileData?: string;                           // 文件数据（base64/dataURL）
  notes?: NoteEntry[];                         // 用户笔记
  whiteboard?: string;                         // Excalidraw 白板数据（JSON）
  whiteboardThumbnail?: string;                // 白板缩略图（data URL）
  cognitionLevel?: number;                     // 1-5 认知档位
  cognitionReason?: string;                    // AI 评审理由
  cognitionHistory?: { level: number; evaluatedAt: string; conversationLength: number }[];
  metadata: NodeMetadata;
}

export interface NodeMetadata {
  source?: string;
  materialType?: MaterialType;
  conversationId?: string;
  domainId?: string;
  scrapedTitle?: string;
  scrapedFavicon?: string;
  createdAt: string;
  updatedAt: string;
}

// ===== 边类型 =====
export type EdgeType = 'hierarchy' | 'association' | 'reference';

export interface KnowledgeEdge {
  id: string;
  boardId: string;
  source: string;
  target: string;
  relation: string;
  type: EdgeType;
  autoGenerated: boolean;
}

// ===== 笔记 =====
export type NoteKind = 'manual' | 'chat' | 'question'; // 手动 / 对话摘录 / 我的提问

export interface NoteEntry {
  id: string;
  content: string;
  kind: NoteKind;
  createdAt: string;
}

// ===== 对话类型 =====
export type ChatMode = 'learn' | 'feynman' | 'debate' | 'design';

// 回答风格：初始 / 适中 / 精简 / 自定义
export type ResponseStyle = 'default' | 'balanced' | 'concise' | 'custom';

export interface Conversation {
  id: string;
  nodeId?: string;
  boardId?: string;
  boardName?: string;
  mode: ChatMode;
  messages: ChatMessage[];
  createdAt: string;
  updatedAt: string;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
}

// ===== 领域图谱 =====
export interface DomainGraph {
  id: string;
  name: string;
  nodeIds: string[];
  createdAt: string;
}

// ===== 推荐 =====
export interface Recommendation {
  id: string;
  title: string;
  description: string;
  reason: string;
  type: 'related' | 'breakthrough';
  category?: 'knowledge' | 'trivia';
  sourceNodeId?: string;
}

// ===== 图谱变更（批量操作） =====
export interface GraphChanges {
  newNodes: KnowledgeNode[];
  updatedNodes: { id: string; updates: Partial<KnowledgeNode> }[];
  newEdges: KnowledgeEdge[];
}
