'use client';

import { useState } from 'react';
import { Globe, Link2, Maximize, ZoomIn, ZoomOut, Dices, Download, FolderTree, Loader2 } from 'lucide-react';
import { useReactFlow } from '@xyflow/react';
import { nanoid } from 'nanoid';
import { useUIStore } from '@/stores/uiStore';
import { useGraphStore } from '@/stores/graphStore';
import { useBoardStore } from '@/stores/boardStore';
import type { KnowledgeNode, KnowledgeEdge } from '@/types';
import { BreakthroughModal } from './BreakthroughModal';
import { ThemeSwitcher } from '@/components/ThemeSwitcher';

interface ThemeResult {
  title: string;
  content: string;
  childNodeTitles: string[];
}

interface ToolbarProps {
  /** 多选节点 ID 集合（Shift+Click），用于"归纳选中" */
  selectedNodeIds?: Set<string>;
}

export function Toolbar({ selectedNodeIds }: ToolbarProps) {
  const { zoomIn, zoomOut, fitView } = useReactFlow();
  const openDomainModal = useUIStore((s) => s.openDomainModal);
  const openImportModal = useUIStore((s) => s.openImportModal);
  const currentBoardId = useBoardStore((s) => s.currentBoardId);
  const [breakthroughOpen, setBreakthroughOpen] = useState(false);
  const [summarizing, setSummarizing] = useState<'all' | 'selected' | null>(null);

  const selectionCount = selectedNodeIds?.size ?? 0;

  // 调用 themes API，将返回的主题生成 theme 节点 + hierarchy 边
  const generateThemes = async (sourceNodes: KnowledgeNode[], target: 'all' | 'selected') => {
    if (!currentBoardId || sourceNodes.length === 0 || summarizing) return;
    setSummarizing(target);
    try {
      const res = await fetch('/api/graph/themes', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          nodes: sourceNodes.map((n) => ({ type: n.type, title: n.title, content: n.content })),
        }),
      });
      if (!res.ok) return;
      const data: { themes?: ThemeResult[] } = await res.json();
      const themes = data.themes ?? [];
      if (themes.length === 0) return;

      const now = new Date().toISOString();
      const newNodes: KnowledgeNode[] = [];
      const newEdges: KnowledgeEdge[] = [];

      for (const theme of themes) {
        const children = sourceNodes.filter((n) => theme.childNodeTitles.includes(n.title));
        if (children.length === 0) continue;

        // 主题节点放在子节点的质心上方
        const avgX = children.reduce((sum, n) => sum + n.position.x, 0) / children.length;
        const avgY = children.reduce((sum, n) => sum + n.position.y, 0) / children.length;
        const themeNode: KnowledgeNode = {
          id: `theme-${nanoid(8)}`,
          boardId: currentBoardId,
          type: 'theme',
          title: theme.title,
          content: theme.content,
          level: 1,
          status: 'lit',
          position: {
            x: avgX + Math.floor(Math.random() * 120 - 60),
            y: avgY - 120 + Math.floor(Math.random() * 60 - 30),
          },
          metadata: { createdAt: now, updatedAt: now },
        };
        newNodes.push(themeNode);

        for (const child of children) {
          newEdges.push({
            id: `edge-${nanoid(8)}`,
            boardId: currentBoardId,
            source: themeNode.id,
            target: child.id,
            relation: '包含',
            type: 'hierarchy',
            autoGenerated: true,
          });
        }
      }

      if (newNodes.length > 0) {
        useGraphStore.getState().applyGraphChanges({ newNodes, updatedNodes: [], newEdges });
      }
    } catch (error) {
      console.error('主题归纳失败:', error);
    } finally {
      setSummarizing(null);
    }
  };

  const handleSummarizeAll = () => {
    generateThemes(useGraphStore.getState().nodes, 'all');
  };

  const handleSummarizeSelected = () => {
    if (!selectedNodeIds || selectedNodeIds.size === 0) return;
    const nodes = useGraphStore.getState().nodes.filter((n) => selectedNodeIds.has(n.id));
    generateThemes(nodes, 'selected');
  };

  const handleExport = () => {
    const { nodes, edges } = useGraphStore.getState();
    const data = {
      version: '0.0.1',
      exportedAt: new Date().toISOString(),
      nodes,
      edges,
    };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `memos-export-${new Date().toISOString().slice(0, 10)}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const buttonClass =
    'p-2 rounded-md hover:bg-[var(--bg-hover)] text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors disabled:opacity-40 disabled:pointer-events-none';

  return (
    <>
    <div className="absolute top-4 left-4 z-10 flex flex-col gap-1 rounded-lg border border-[var(--border)] bg-[var(--bg-secondary)]/80 backdrop-blur-sm p-1.5 shadow-lg">
      <button
        onClick={openDomainModal}
        className={buttonClass}
        title="生成领域图谱"
      >
        <Globe size={18} />
      </button>

      <button
        onClick={openImportModal}
        className={buttonClass}
        title="导入材料"
      >
        <Link2 size={18} />
      </button>

      <button
        onClick={handleSummarizeAll}
        className={buttonClass}
        title="自动归纳主题"
        disabled={summarizing !== null}
      >
        {summarizing === 'all' ? <Loader2 size={18} className="animate-spin" /> : <FolderTree size={18} />}
      </button>

      {/* 多选时出现：归纳选中节点 */}
      {selectionCount >= 2 && (
        <button
          onClick={handleSummarizeSelected}
          disabled={summarizing !== null}
          className="flex items-center gap-1.5 px-2 py-1.5 rounded-md whitespace-nowrap text-[11px] font-medium bg-[var(--accent-soft)] text-[var(--accent)] hover:brightness-125 disabled:opacity-40 disabled:pointer-events-none transition-all"
          title="基于选中节点归纳主题"
        >
          {summarizing === 'selected' ? <Loader2 size={14} className="animate-spin" /> : <FolderTree size={14} />}
          归纳选中 ({selectionCount})
        </button>
      )}

      <button
        onClick={() => setBreakthroughOpen(true)}
        className={buttonClass}
        title="给我个惊喜"
      >
        <Dices size={18} />
      </button>

      <button
        onClick={handleExport}
        className={buttonClass}
        title="导出图谱"
      >
        <Download size={18} />
      </button>

      <div className="my-1 border-t border-[var(--border)]" />

      <button
        onClick={() => fitView({ duration: 300 })}
        className={buttonClass}
        title="适配视图"
      >
        <Maximize size={18} />
      </button>

      <button
        onClick={() => zoomIn({ duration: 200 })}
        className={buttonClass}
        title="放大"
      >
        <ZoomIn size={18} />
      </button>

      <button
        onClick={() => zoomOut({ duration: 200 })}
        className={buttonClass}
        title="缩小"
      >
        <ZoomOut size={18} />
      </button>
    
      <div className="my-1 border-t border-[var(--border)]" />
    
      <ThemeSwitcher />
    
      {/* 破茧推荐弹窗（渲染在 Toolbar 外层，以避免 fixed 定位被影响） */}
    </div>
    <BreakthroughModal visible={breakthroughOpen} onClose={() => setBreakthroughOpen(false)} />
    </>
  );
}
